import csv

def generate_header(csv_path, output_path):
    with open(csv_path, "r") as f_in, open(output_path, "w") as f_out:
        reader = csv.DictReader(f_in)
        f_out.write("// GenerateHeaders.py AUTOGENERATED FILE--DO NOT EDIT!\n")
        f_out.write("#pragma once\n")
        f_out.write("#include <type_traits>\n\n")
        
        for row in reader:
            # Strip any leading/trailing whitespace
            type_str = row["Type"].strip()
            name = row["Name"].strip()
            addr = row["Address"].strip()
            
            # Generate macro
            macro = f"#define {name} (*reinterpret_cast<std::add_pointer_t<{type_str}>>({addr}))\n"
            f_out.write(macro)

if __name__ == "__main__":
    generate_header("./core/globals.csv", "./core/include/GeneratedSymbols.h")