import csv

def generate_header(csv_path, output_path):
    with open(csv_path, "r") as f_in, open(output_path, "w") as f_out:
        reader = csv.DictReader(f_in)
        f_out.write("// GenerateHeaders.py AUTOGENERATED FILE--DO NOT EDIT!\n")
        f_out.write("#pragma once\n")
        f_out.write(
"namespace th11 {\n\
    // Stripped down add_pointer\n\
    template <typename T>\n\
    struct add_pointer {\n\
        using type = T*; \n\
    };\n\
    template <typename T> struct add_pointer<T&> { using type = T*; };\n\
    template <typename T>\n\
    using add_pointer_t = typename add_pointer<T>::type;\n\
}\n\n"
)
        
        for row in reader:
            # Strip any leading/trailing whitespace
            type_str = row["Type"].strip()
            name = row["Name"].strip()
            addr = row["Address"].strip()
            
            # Generate macro
            macro = f"#define {name} (*reinterpret_cast<th11::add_pointer_t<{type_str}>>({addr}))\n"
            f_out.write(macro)

if __name__ == "__main__":
    generate_header("./core/globals.csv", "./core/include/GeneratedSymbols.h")